version: '3'
services:
  server:
    image: feature-requests:local
    build:
      context: .
    volumes:
      - .:/usr/local/src
    ports:
      - $PORT:5000
    environment:
      - DATABASE_CONNECTION
    command:
      - python
      - main.py
    depends_on:
      - database
  database:
    image: postgres:9.6-alpine
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
